{
 "title": "Dashboard NodeJs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "APONTAMENTOS",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "content": "\n# Dashboard NodeJs for Anderson Braz\n\nServices:\n\nGET Alphabet | GET Members | Metrics for Prometheus |\n------------ | ------------- | ------------- |\n[http://nodejs-service:9000/alphabet](http://nodejs-service:9000/alphabet) | [http://nodejs-service:9000/members](http://nodejs-service:9000/members) | [http://nodejs-service:9000/metrics](http://nodejs-service:9000/metrics) |\n\n\n"
  },
  {
   "title": "POST  with SUCCESS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sample_summary_count{method=\"POST\",status_code=\"200\"}"
    }
   ]
  },
  {
   "title": "GET with SUCCESS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sample_summary_count{method=\"GET\",status_code=\"200\"}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(my_api_nodejs_gc_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}