version: '3.7'
services:

    # nodejs-express-api
    nodejs-service:
        image: nodejs-api:1.0
        container_name: nodejs-service
        ports:
            - 9000:9000
        networks:
            - metrics_network

    # prometheus
    prometheus-server:
        image: prom/prometheus
        container_name: prometheus-server
        ports:
            - 9090:9090
        networks:
            - metrics_network
        volumes:
            - "/Users/andersonbraz/Docker/my_metrics/config/prometheus.yml:/etc/prometheus/prometheus.yml"
    
    # grafana
    grafana:
        image: grafana/grafana
        container_name: grafana-server
        ports:
            - '3000:3000'
        depends_on:
            - nodejs-service
        networks:
            - metrics_network

networks: 
    metrics_network:
        driver: bridge