# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

 - job_name: 'prometheus'
   scrape_interval: 15s
   scrape_timeout: 10s
   static_configs:
     - targets: ['prometheus-server:9090']
#
# - job_name: 'node-api'
#   scheme: https
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   tls_config:
#     insecure_skip_verify: true
#   static_configs:
#     - targets: ['nodejs-service:9000']